### ISSUE TITLE
Fehler in den Folien

### ISSUE THREAD

**Issue by Feliix42** [fsr/c-lessons#3]
Die Folien mit dem Titel **"OSs you may use"** brauchen dringend eine Überarbeitung.
Unter OS X ist die Installation von gcc genau so einfach wie unter jedem anderen unixoiden System. Mit `brew install gcc` oder der Installation von XCode hat man alles, was man braucht und kann damit genau so gut arbeiten, wie mit Linux. Ich weiß nicht, was das Bild mit dem Gameboy und den Äpfeln da soll. Man sollte die Erstsemestler (die den Kurs vor allem besuchen) nicht durch sowas abschrecken, zumal das Bild dann eigentlich einem anderen OS zugeordnet werden sollte, bei dem schon allein die Installation des Compilers fast 10 Schritte erfordert. :smile:

**Comment by Lodifice** [comment]
Information on Mac OS usage has been added. However, only a minority among the tutors has experience in using Mac OS - therefore, we cannot force them to "support" it by answering questions specific to Mac OS. If you have some expertise, feel free to help your students. The images are considered to be art, if you come up with something more funny, open a pull request.

**Comment by Feliix42** [comment]
Yeah, a bilingual issue! :smile:
Thanks for the edit. Of course, you can't force the tutors and it was not my intention to do so. Just wanted to point out that you _can_ use all platforms for development.
